# TOML v0.5.0

# "A-D" means [A, B, C, D]. "A&C&E" means [A, C, E]. "A&C-E" means [A, C, D, E].

[files]
output.prefix = "example"
output.path   = "./"
output.format = "xyz"

[simulator]
# The same as Mjolnir.
precision       = "double"
boundary_type   = "Unlimited"
type            = "MolecularDynamics"
delta_t         = 0.4
total_step      = 50_000
save_step       = 100
integrator.type = "BAOABLangevin"
integrator.seed = 2374

[[systems]]
attribute.temperature    = 300.0 # [K]
attribute.ionic_strength = 0.1   # [mol/L]
boundary_shape           = {}    # unlimited boundary

# path/to/directory/that/contains/pdb/files
path.pdb      = "./data/pdb/"
# <group-name> = <tableof: pdb file and model name>
# The same group-name would be used in `[[forcefields]]` table.
# you can use `[A-Za-z0-9_]+`. Note that `-` is considered as a name-separator.
protein       = {reference = "example.pdb", model = "AICG2+", chain="A-D"}

DNA.reference = "DNA.pdb"
DNA.initial   = "bend_DNA.pdb"
DNA.model     = "3SPN2"
DNA.chain     = "A-B"

[[forcefields]]
# parameter file for this forcefield
parameters    = "./parameter/parameters.toml"

[forcefields.local]
protein = ["ClementiGo"]

[forcefields.global]
protein     = ["GoContact", "ExcludedVolume"]
DNA         = ["3SPN2",     "Electrostatic"]
protein-DNA = [
    {name = "GoContact", k = 0.1},
    "Electrostatic"
]
