# this file is for jarngreipr.
# "A-D" means [A, B, C, D]. "A&C&E" means [A, C, E]. "A&C-E" means [A, C, D, E].

[general]
toml_prefix   = "example1"
output_prefix = "lala"
output_path   = "./"
format        = "gromacs"
format_prefix = "genesis"
parameters    = "./parameter/parameters.toml"
precision     = "double"
thread        = false
gpu           = false

[[structures]]
protein = {file = "./data/pdb/example.pdb", model = "CarbonAlpha", chain="A-D"}
DNA     = {file = "./data/pdb/DNA.pdb",     model = "3SPN2",       chain="A"}
# To specify the initial conformation that is differrent from reference
# structure, define `initial`.

[simulator]
type       = "Molecular Dynamics"
scheme     = "Underdamped Langevin"
delta_t    = 0.4    # the unit [tau] depends on the forcefield and parameters
total_step = 50_000 # the total simulation time will be 0.4 * 50000 = 20000.
save_step  = 100    # each 40 [tau], the configurations are saved.
boundary.type  = "Unlimited"
boundary.shape = {}
#boundary.type  = "PeriodicCuboid"
#boundary.shape = {lower = [0.0, 0.0, 0.0], upper = [10.0, 10.0, 10.0]}

[[systems]]
temperature    = 300.0 # [K]
seed           = 2374
ionic_strength = 0.1   # [mol/L]

[[forcefields]]
# the energy become the sum of these.
[forcefields.local]
protein = [{name = "ClementiGo"}]
[forcefields.global]
protein = [{name = "GoContact"}, {name = "ExcludedVolume"}]
protein-DNA = [
    {name = "GoContact"},
    {name = "Electrostatic"}
]
