# TOML v0.5.0

[files]
output.prefix = "example"
output.path   = "./"
output.format = "xyz"

[simulator]
# The same as Mjolnir.
precision       = "double"
boundary_type   = "Unlimited"
type            = "MolecularDynamics"
delta_t         = 0.4
total_step      = 50_000
save_step       = 100
integrator.type = "BAOABLangevin"
integrator.seed = 2374

[[systems]]
attribute.temperature    = 300.0 # [K]
attribute.ionic_strength = 0.1   # [mol/L]
boundary_shape           = {}    # unlimited boundary

# path/to/directory/that/contains/pdb/files
path.pdb      = "./data/pdb/"

# <group-name> = <tableof: pdb file and model name>
# The same group-name would be used in `[[forcefields]]` table.
# you can use `[A-Za-z0-9_]+`. Note that `-` is considered as a name-separator.
protein       = {reference = "example.pdb", model = "AICG2+", chain="A-D"}

DNA.reference = "DNA.pdb"
DNA.initial   = "bend_DNA.pdb"
DNA.model     = "3SPN2"
DNA.chain     = "A-B"

[[forcefields]]
# parameter file for this forcefield
parameters    = "./parameter/parameters.toml"

[[forcefields.local]]
# including inter-chain Go
potential = "AICG2+"
group     = ["protein"]

[[forcefields.local]]
potential = "3SPN2"
group     = ["DNA"]

[[forcefields.local]]
# Go-contact is applied between specific pairs of particles, so classified as local
potential = "GoContact"
group.inter = ["DNA", "protein"]

[[forcefields.global]]
# inter- and intra-chain protein-protein GoContact and ExcludedVolume will be applied
potential = "AICG2+"
groups.intra = ["protein"]

[[forcefields.global]]
# DNA-DNA DebyeHuckel and WCA potential will be applied
potential = "3SPN2"
groups.intra = ["DNA"]

[[forcefields.global]]
# inter-chain DNA-Protein ExcludedVolume will be applied
potential = "ExcludedVolume"
groups.inter = ["DNA", "protein"]

[[forcefields.global]]
# DNA-Protein DebyeHuckel will be applied
potential = "DebyeHuckel"
groups.inter = ["DNA", "protein"]
