# this file is for jarngreipr.
# "A-D" means [A, B, C, D]. "A&C&E" means [A, C, E]. "A&C-E" means [A, C, D, E].

[general]
file_prefix = "example1"
output_path = "./"
parameters  = "./parameter/parameters.toml"
boundary    = "Unlimited"
precision   = "double"
thread      = false
gpu         = false
seed        = 2374

[[structures]]
A-D = {file = "./data/pdb/example.pdb", model = "CarbonAlpha"}
# To specify the initial conformation that is differrent from reference
# structure, define `initial`.
# A-D = {file = "./data/pdb/example.pdb", initial = "./data/pdb/example2.pdb", model = "CarbonAlpha"}

[simulator]
type       = "Molecular Dynamics"
scheme     = "Underdamped Langevin"
delta_t    = 0.4    # the unit [tau] depends on the forcefield and parameters
total_step = 50_000 # the total simulation time will be 0.4 * 50000 = 20000.
save_step  = 100    # each 40 [tau], the configurations are saved.

[[systems]]
temperature    = 300.0       # [K]
ionic_strength = 0.1         # [mol/L]
boundary       = {}
# boundary     = {lower = [0.0, 0.0, 0.0], upper = [10.0, 10.0, 10.0]}

[[forcefields]]
# the energy become the sum of these.
[forcefields.local]
A-D = [{name = "ClementiGo"},]
[forcefields.global]
A-D = [{name = "GoContact"}, {name = "ExcludedVolume"}]
