epsilon = 0.2

[radii]
# TODO
ALA = 2.0
ARG = 2.0
ASN = 2.0
ASP = 2.0
CYS = 2.0
GLN = 2.0
GLU = 2.0
GLY = 2.0
HIS = 2.0
ILE = 2.0
LEU = 2.0
LYS = 2.0
MET = 2.0
PHE = 2.0
PRO = 2.0
SER = 2.0
THR = 2.0
TRP = 2.0
TYR = 2.0
VAL = 2.0
