[mass]
H   =  1.0080
P   = 30.9738
O   = 15.9994
C   = 12.0107
N   = 14.0067

[mass."AICG2+"]

ALA =  71.09
ARG = 156.19
ASN = 114.11
ASP = 115.09
CYS = 103.15
GLN = 128.14
GLU = 129.12
GLY =  57.05
HIS = 137.14
ILE = 113.16
LEU = 113.16
LYS = 128.17
MET = 131.19
PHE = 147.18
PRO =  97.12
SER =  87.08
THR = 101.11
TRP = 186.21
TYR = 163.18
VAL =  99.14

[mass.3SPN2]
# phosphate mass is independent from base kind
PA =  94.9696 # Phosphate of Adenine
PT =  94.9696 # Phosphate of Thymine
PC =  94.9696 # Phosphate of Cytosine
PG =  94.9696 # Phosphate of Guanine
# sugar mass is independent from base kind
SA =  83.1104 # Sugar of Adenine
ST =  83.1104 # Sugar of Thymine
SC =  83.1104 # Sugar of Cytosine
SG =  83.1104 # Sugar of Guanine
# base mass depends on base kind (of course).
BA = 134.1220 # Base of Adenine
BT = 125.1078 # Base of Thymine
BC = 110.0964 # Base of Cytosine
BG = 150.1214 # Base of Guanine
